# Generated by Django 5.0 on 2025-04-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_prediagnosisreport_treatment_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('title', models.CharField(choices=[('chief', '主任医师'), ('associate_chief', '副主任医师'), ('attending', '主治医师')], max_length=20, verbose_name='职称')),
                ('years_of_experience', models.IntegerField(verbose_name='执业年限')),
                ('hospital', models.CharField(max_length=100, verbose_name='主要执业医院')),
                ('department', models.CharField(max_length=50, verbose_name='科室')),
                ('specialty', models.TextField(verbose_name='专长领域')),
                ('tcm_patterns', models.CharField(help_text='用逗号分隔的证型列表', max_length=200, verbose_name='擅长证型')),
                ('rating', models.FloatField(default=5.0, verbose_name='评分')),
                ('patients_count', models.IntegerField(default=0, verbose_name='接诊量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '医生',
                'verbose_name_plural': '医生',
                'ordering': ['-rating', '-patients_count'],
            },
        ),
    ]
